/**
 * main.cpp — Client Bootstrap
 *
 * First-run behaviour:
 *   1. Generates a random client ID (saved to secrets/config.txt)
 *   2. Connects to the server via TCP and sends: REGISTER <client_id>
 *   3. Server responds with an assigned port number
 *   4. Saves server IP + assigned port to secrets/config.txt
 *   5. Spawns heartbeat and receiver as child processes
 *
 * Subsequent runs:
 *   - Reads existing secrets/config.txt and skips registration
 *   - Goes straight to spawning heartbeat + receiver
 *
 * Cross-platform: Windows (Winsock2) + Linux/macOS (POSIX sockets)
 *
 * Compile (Linux/macOS):
 *   g++ -std=c++17 -o main main.cpp -pthread
 *
 * Compile (Windows MSVC):
 *   cl /EHsc /std:c++17 main.cpp ws2_32.lib
 *
 * Compile (Windows MinGW):
 *   g++ -std=c++17 -o main main.cpp -lws2_32
 */

#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <cstring>
#include <ctime>
#include <cstdlib>
#include <random>
#include <filesystem>

#ifdef _WIN32
    #include <winsock2.h>
    #include <ws2tcpip.h>
    #pragma comment(lib, "ws2_32.lib")
    using SocketType = SOCKET;
    #define INVALID_SOCK  INVALID_SOCKET
    #define CLOSE_SOCKET  closesocket
    #define SOCK_ERR      SOCKET_ERROR
#else
    #include <sys/socket.h>
    #include <netinet/in.h>
    #include <arpa/inet.h>
    #include <unistd.h>
    using SocketType = int;
    #define INVALID_SOCK  -1
    #define CLOSE_SOCKET  close
    #define SOCK_ERR      -1
#endif

// ─── Configuration ────────────────────────────────────────────────────────────
static const char*    SERVER_IP          = "72.60.221.128";
static const uint16_t REGISTER_PORT      = 8000;       // Server's registration TCP port
static const char*    SECRETS_DIR        = "../secrets";
static const char*    SECRETS_FILE       = "../secrets/config.txt";
static const char*    HEARTBEAT_BINARY   = "./heartbeat";
static const char*    RECEIVER_BINARY    = "./receiver";
static const int      CLIENT_ID_LENGTH   = 16;         // Random ID character length
// ─────────────────────────────────────────────────────────────────────────────

struct ClientConfig {
    std::string clientId;
    std::string serverIp;
    uint16_t    assignedPort = 0;
};

// ── Helpers ──────────────────────────────────────────────────────────────────

std::string timestamp() {
    std::time_t t = std::time(nullptr);
    char buf[32];
    std::strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", std::localtime(&t));
    return buf;
}

void log(const std::string& level, const std::string& msg) {
    std::cout << "[" << timestamp() << "] [" << level << "] " << msg << "\n";
}

// Generates a random alphanumeric string of given length
std::string generateClientId(int length) {
    static const char charset[] =
        "abcdefghijklmnopqrstuvwxyz"
        "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        "0123456789";
    std::mt19937 rng(std::random_device{}());
    std::uniform_int_distribution<int> dist(0, sizeof(charset) - 2);
    std::string id;
    id.reserve(length);
    for (int i = 0; i < length; i++)
        id += charset[dist(rng)];
    return id;
}

// Trims trailing whitespace/newlines from a string
std::string trim(const std::string& s) {
    size_t end = s.find_last_not_of(" \t\r\n");
    return (end == std::string::npos) ? "" : s.substr(0, end + 1);
}

// ── Config file I/O ──────────────────────────────────────────────────────────

// Reads secrets/config.txt
// Format:
//   client_id=<id>
//   server_ip=<ip>
//   assigned_port=<port>
bool loadConfig(ClientConfig& cfg) {
    std::ifstream f(SECRETS_FILE);
    if (!f.is_open()) return false;

    std::string line;
    while (std::getline(f, line)) {
        line = trim(line);
        if (line.empty() || line[0] == '#') continue;

        auto eq = line.find('=');
        if (eq == std::string::npos) continue;

        std::string key = trim(line.substr(0, eq));
        std::string val = trim(line.substr(eq + 1));

        if (key == "client_id")     cfg.clientId     = val;
        else if (key == "server_ip")     cfg.serverIp     = val;
        else if (key == "assigned_port") cfg.assignedPort = static_cast<uint16_t>(std::stoi(val));
    }

    return !cfg.clientId.empty() && cfg.assignedPort != 0;
}

// Writes config to secrets/config.txt
bool saveConfig(const ClientConfig& cfg) {
    // Create secrets dir if it doesn't exist
    std::error_code ec;
    std::filesystem::create_directories(SECRETS_DIR, ec);
    if (ec) {
        log("ERROR", "Could not create secrets directory: " + ec.message());
        return false;
    }

    std::ofstream f(SECRETS_FILE, std::ios::trunc);
    if (!f.is_open()) {
        log("ERROR", "Could not write to: " + std::string(SECRETS_FILE));
        return false;
    }

    f << "# Auto-generated by main.cpp — do not edit manually\n";
    f << "client_id="     << cfg.clientId     << "\n";
    f << "server_ip="     << cfg.serverIp     << "\n";
    f << "assigned_port=" << cfg.assignedPort << "\n";
    return true;
}

// ── Network: Registration ─────────────────────────────────────────────────────

// Connects to server, sends REGISTER <client_id>, receives assigned port
// Protocol:
//   Client → "REGISTER <client_id>\n"
//   Server → "PORT <number>\n"  on success
//   Server → "ERROR <reason>\n" on failure
bool registerWithServer(ClientConfig& cfg) {
    log("INFO", "Connecting to server " + std::string(SERVER_IP) +
        ":" + std::to_string(REGISTER_PORT) + " for registration...");

    SocketType sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (sock == INVALID_SOCK) {
        log("ERROR", "Failed to create TCP socket.");
        return false;
    }

    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_port   = htons(REGISTER_PORT);
    if (inet_pton(AF_INET, SERVER_IP, &addr.sin_addr) <= 0) {
        log("ERROR", "Invalid server IP: " + std::string(SERVER_IP));
        CLOSE_SOCKET(sock);
        return false;
    }

    if (connect(sock, reinterpret_cast<sockaddr*>(&addr), sizeof(addr)) == SOCK_ERR) {
        log("ERROR", "Could not connect to registration server.");
        CLOSE_SOCKET(sock);
        return false;
    }

    // Send registration message
    std::string msg = "REGISTER " + cfg.clientId + "\n";
    send(sock, msg.c_str(), static_cast<int>(msg.size()), 0);
    log("INFO", "Sent: " + trim(msg));

    // Receive response
    char buf[256] = {};
    int  n        = recv(sock, buf, sizeof(buf) - 1, 0);
    CLOSE_SOCKET(sock);

    if (n <= 0) {
        log("ERROR", "No response from server.");
        return false;
    }

    std::string response = trim(std::string(buf, n));
    log("INFO", "Server responded: " + response);

    // Parse "PORT <number>"
    if (response.substr(0, 5) == "PORT ") {
        try {
            cfg.assignedPort = static_cast<uint16_t>(std::stoi(response.substr(5)));
            cfg.serverIp     = SERVER_IP;
            return true;
        } catch (...) {
            log("ERROR", "Could not parse port from: " + response);
            return false;
        }
    }

    log("ERROR", "Unexpected server response: " + response);
    return false;
}

// ── Process spawning ─────────────────────────────────────────────────────────

void spawnProcess(const std::string& binary, const std::string& arg) {
#ifdef _WIN32
    std::string cmd = binary + " " + arg;
    STARTUPINFOA si{};
    si.cb = sizeof(si);
    PROCESS_INFORMATION pi{};
    if (!CreateProcessA(nullptr, const_cast<char*>(cmd.c_str()),
                        nullptr, nullptr, FALSE,
                        CREATE_NEW_CONSOLE, nullptr, nullptr, &si, &pi)) {
        log("ERROR", "Failed to spawn: " + cmd);
    } else {
        log("INFO", "Spawned process: " + cmd + " (PID " + std::to_string(pi.dwProcessId) + ")");
        CloseHandle(pi.hProcess);
        CloseHandle(pi.hThread);
    }
#else
    pid_t pid = fork();
    if (pid == 0) {
        // Child process
        execl(binary.c_str(), binary.c_str(), arg.c_str(), nullptr);
        std::cerr << "[ERROR] execl failed for: " << binary << "\n";
        _exit(1);
    } else if (pid > 0) {
        log("INFO", "Spawned process: " + binary + " " + arg + " (PID " + std::to_string(pid) + ")");
    } else {
        log("ERROR", "fork() failed for: " + binary);
    }
#endif
}

// ── Main ─────────────────────────────────────────────────────────────────────

int main() {
    log("INFO", "=== Fleet Manager Client Bootstrap ===");

#ifdef _WIN32
    WSADATA wsaData;
    if (WSAStartup(MAKEWORD(2, 2), &wsaData) != 0) {
        log("ERROR", "WSAStartup failed.");
        return 1;
    }
#endif

    ClientConfig cfg;
    bool firstRun = false;

    if (loadConfig(cfg)) {
        log("INFO", "Existing config found.");
        log("INFO", "Client ID    : " + cfg.clientId);
        log("INFO", "Server IP    : " + cfg.serverIp);
        log("INFO", "Assigned port: " + std::to_string(cfg.assignedPort));
    } else {
        firstRun    = true;
        cfg.clientId = generateClientId(CLIENT_ID_LENGTH);
        log("INFO", "First run detected. Generated client ID: " + cfg.clientId);

        if (!registerWithServer(cfg)) {
            log("ERROR", "Registration failed. Exiting.");
#ifdef _WIN32
            WSACleanup();
#endif
            return 1;
        }

        if (!saveConfig(cfg)) {
            log("ERROR", "Failed to save config. Exiting.");
#ifdef _WIN32
            WSACleanup();
#endif
            return 1;
        }

        log("INFO", "Registration successful.");
        log("INFO", "Assigned port: " + std::to_string(cfg.assignedPort));
        log("INFO", "Config saved to: " + std::string(SECRETS_FILE));
    }

    (void)firstRun; // reserved for future first-run setup steps

    // Spawn heartbeat and receiver, passing secrets file path as argument
    log("INFO", "Spawning heartbeat...");
    spawnProcess(HEARTBEAT_BINARY, SECRETS_FILE);

    log("INFO", "Spawning receiver...");
    spawnProcess(RECEIVER_BINARY, SECRETS_FILE);

    log("INFO", "Bootstrap complete. Both processes launched.");

#ifdef _WIN32
    WSACleanup();
#endif
    return 0;
}